### PR TITLE
add Mariatta video on Sponsor page

### PR DESCRIPTION
**Pull request by reshamas**
:books: Documentation preview en :books:: https://pymc-data-umbrella--203.org.readthedocs.build/en/203/

:books: Documentation preview es :books:: https://pymc-data-umbrella-es--203.org.readthedocs.build/es/203/

:books: Documentation preview pt :books:: https://pymc-data-umbrella-pt--203.org.readthedocs.build/pt/203/

### CODE REVIEW

**Review by OriolAbril — COMMENTED** [review]
do we want participants to watch the video or do we want prospective sponsors to do so?

**Comment by reshamas** [comment]
> do we want participants to watch the video or do we want prospective sponsors to do so?

It's more so for the participants.

**Comment by OriolAbril** [comment]
I would put it in https://pymc-data-umbrella.xyz/en/latest/about/index.html or https://pymc-data-umbrella.xyz/en/latest/sprint/index.html. The sponsors page has very little traffic and I don't see it being very participant oriented

**Comment by reshamas** [comment]
> I would put it in https://pymc-data-umbrella.xyz/en/latest/about/index.html or https://pymc-data-umbrella.xyz/en/latest/sprint/index.html. The sponsors page has very little traffic and I don't see it being very participant oriented

Moved it to the event page:
https://pymc-data-umbrella.xyz/en/latest/2023-03_sprint/index.html

**Pull request merged**
