### PR TITLE
Add contributor pic

### PR DESCRIPTION
**Pull request by LucyJimenez**
Upload fist photo contributor.

### CODE REVIEW

**Comment by reshamas** [comment]
@LucyJimenez 
This is the link to the build:
https://pymc-data-umbrella--128.org.readthedocs.build/en/128/2022-07_sprint/schedule.html

More specifically, the page:
https://pymc-data-umbrella--128.org.readthedocs.build/en/128/2022-07_sprint/sprint_parties/contributors.html

It looks like you added a bunch of photos, but only 2 photos seem to appear.  Not sure why.

@cluhmann Any idea why?

**Comment by LucyJimenez** [comment]
Yes, I'm doing some test to find Wich is the best way to show the pictures.

**Comment by LucyJimenez** [comment]
Yes, I'm doing some test to find Wich is the best way to show the pictures.

**Comment by reshamas** [comment]
@LucyJimenez It's also interesting that there are no errors.

**Comment by LucyJimenez** [comment]
> @LucyJimenez It's also interesting that there are no error messages.

Let me try it again :)

**Comment by reshamas** [comment]
Thanks @LucyJimenez

**Pull request merged**
